_target_: src.models.view_comprehensive.ViewComprehensiveEmbeddingModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.vlm_autoencoder.VLMAutoencoder

  encoder_input_size: 512
  encoder_n_hidden_layers: 2
  encoding_size: 128

loss:
  _target_: src.models.components.losses.LossAutoencoder
  weight_similarity: 0.5
  weigth_autoencoder: 0.5
  reg_vd: 0.0

# compile model for faster training with pytorch 2.0
compile: false