_target_: src.models.view_invariant.ViewInvariantEmbeddingModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.vlm_head.VLMHead
  input_size: 512 # based on CLIP 
  hidden_size: 2048
  n_hidden_layers: 3 # number of hidden layers
  output_size: 512

# compile model for faster training with pytorch 2.0
compile: false
